version: "3.9"
# by default when run docker compose it runs containers with --rm -d
# by default docker compose defines a network for all services and add them together
services:
  database:
    image: "mongo"
    volumes:
      - "./database:/data/db"
  backend:
    depends_on:
      - "database"
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - "5001:80"
    volumes:
      - "./backend:/app"
      - "./logs:/app/logs"
      - "/app/node_modules"
  frontend:
    depends_on:
      - "database"
      - "backend"
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - "5000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true